
// NOTE: The ABIs in this file may be truncated and are for initial development.
// They might need to be updated with the full versions if certain functions are missing.

export const AIAgentAddress = "0xC79157189380c3b5ab7fF25f622DaA1e2Cf5FcB5";
export const TaskMarketplaceAddress = "0x65bfDa8Eb3eeD4b90240C7640D0B49450a83E021";
export const GameSimulatorAddress = "0x0b93c6Ce4A04dce967cB0fA0b046001c49F2AD02";

export const AIAgentABI = [{"type":"constructor","inputs":[{"name":"initialOwner","type":"address","internalType":"address"}],"stateMutability":"nonpayable"},{"type":"function","name":"agents","inputs":[{"name":"","type":"uint256","internalType":"uint256"}],"outputs":[{"name":"tokenId","type":"uint256","internalType":"uint256"},{"name":"skill","type":"uint8","internalType":"enum AIAgent.Skill"}],"stateMutability":"view"},{"type":"function","name":"approve","inputs":[{"name":"to","type":"address","internalType":"address"},{"name":"tokenId","type":"uint256","internalType":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},{"type":"function","name":"balanceOf","inputs":[{"name":"owner","type":"address","internalType":"address"}],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},{"type":"function","name":"getAgentSkill","inputs":[{"name":"tokenId","type":"uint256","internalType":"uint256"}],"outputs":[{"name":"","type":"uint8","internalType":"enum AIAgent.Skill"}],"stateMutability":"view"},{"type":"function","name":"getApproved","inputs":[{"name":"tokenId","type":"uint256","internalType":"uint256"}],"outputs":[{"name":"","type":"address","internalType":"address"}],"stateMutability":"view"},{"type":"function","name":"isApprovedForAll","inputs":[{"name":"owner","type":"address","internalType":"address"},{"name":"operator","type":"address","internalType":"address"}],"outputs":[{"name":"","type":"bool","internalType":"bool"}],"stateMutability":"view"},{"type":"function","name":"mint","inputs":[{"name":"to","type":"address","internalType":"address"},{"name":"skill","type":"uint8","internalType":"enum AIAgent.Skill"}],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"nonpayable"},{"type":"function","name":"name","inputs":[],"outputs":[{"name":"","type":"string","internalType":"string"}],"stateMutability":"view"},{"type":"function","name":"owner","inputs":[],"outputs":[{"name":"","type":"address","internalType":"address"}]}] as const;

export const TaskMarketplaceABI = [{"type":"constructor","inputs":[{"name":"_aiAgentContractAddress","type":"address","internalType":"address"}],"stateMutability":"nonpayable"},{"type":"function","name":"acceptTask","inputs":[{"name":"taskId","type":"uint256","internalType":"uint256"},{"name":"agentId","type":"uint256","internalType":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},{"type":"function","name":"aiAgentContract","inputs":[],"outputs":[{"name":"","type":"address","internalType":"contract AIAgent"}],"stateMutability":"view"},{"type":"function","name":"completeTask","inputs":[{"name":"taskId","type":"uint256","internalType":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},{"type":"function","name":"getTask","inputs":[{"name":"taskId","type":"uint256","internalType":"uint256"}],"outputs":[{"name":"","type":"tuple","internalType":"struct TaskMarketplace.Task","components":[{"name":"taskId","type":"uint256","internalType":"uint256"},{"name":"employer","type":"address","internalType":"address"},{"name":"reward","type":"uint256","internalType":"uint256"},{"name":"description","type":"string","internalType":"string"},{"name":"requiredSkill","type":"uint8","internalType":"enum AIAgent.Skill"},{"name":"status","type":"uint8","internalType":"enum TaskMarketplace.TaskStatus"},{"name":"assignedAgentOwner","type":"address","internalType":"address"},{"name":"assignedAgentId","type":"uint256","internalType":"uint256"}]}],"stateMutability":"view"},{"type":"function","name":"owner","inputs":[],"outputs":[{"name":"","type":"address","internalType":"address"}],"stateMutability":"view"},{"type":"function","name":"postTask","inputs":[{"name":"description","type":"string","internalType":"string"},{"name":"reward","type":"uint256","internalType":"uint256"},{"name":"requiredSkill","type":"uint8","internalType":"enum AIAgent.Skill"}],"outputs":[],"stateMutability":"payable"}] as const;

export const GameSimulatorABI = [{"type":"constructor","inputs":[{"name":"_taskMarketplaceAddress","type":"address","internalType":"address"}],"stateMutability":"nonpayable"},{"type":"function","name":"performTask","inputs":[{"name":"taskId","type":"uint256","internalType":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},{"type":"function","name":"taskMarketplace","inputs":[],"outputs":[{"name":"","type":"address","internalType":"contract TaskMarketplace"}],"stateMutability":"view"},{"type":"function","name":"woodInventory","inputs":[{"name":"","type":"address","internalType":"address"}],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"}] as const;
